export default [
  "Starter",
  "Route 1",
  "Nouvaria City (Starter)",
  "Aquarellia (Angeln)",
  "Route 2",
  "Nouvaria-Wald",
  "Route 3",
  "Illumina City (Geschenk)",
  "Route 4",
  "Route 5",
  "Route 6",
  "Route 7",
  "Kampffarm (Geschenk)",
  "Route 8",
  "Relivera City (Angeln)",
  "Relivera-Tunnel",
  "Route 9",
  "Cyllage City (Angeln/Surfen)",
  "Route 10",
  "Refugium des Lebens",
  "Route 11",
  "Spiegellabyrinth",
  "Route 12",
  "Azurküste (Angeln/Surfen)",
  "Route 13",
  "Route 14",
  "Illumina City (Geschenk #2)",
  "Route 15",
  "Route 16",
  "Feenquelle",
  "Pokémon-Village",
  "Route 17",
  "Route 18",
  "Terrorhöhle",
  "Route 19",
  "Route 20",
  "Blizzarville (Geschenk)",
  "Siegesstraße"
];