export default [
  "Starter",
  "Route 101 (Gras)",
  "Route 103 (Gras)",
  "Route 102 (Gras)",
  "Route 104 (Gras)",
  "Blütenburgwald (Gras)",
  "Metarost City (Fossil)",
  "Route 116 (Gras)",
  "Metaflurtunnel (Höhle)",
  "Granithöhle",
  "Blütenburg City (Angeln)",
  "Fausthaven (Angeln)",
  "Route 105 (Surfen)",
  "Route 106 (Angeln)",
  "Route 107 (Angeln)",
  "Route 115 (Angeln)",
  "Route 108 (Angeln)",
  "Route 109 (Angeln)",
  "Graphitport City (Angeln)",
  "Route 110 (Gras)",
  "Route 118 (Angeln)",
  "Route 111 (Gras)",
  "Route 117 (Gras)",
  "Malvenfroh City (Stadt (eventuell Geschenk))",
  "Laubwechselfeld (Gras)",
  "Route 112 (Gras)",
  "Route 113 (Gras)",
  "Route 114 (Gras)",
  "Fallarbor Town (Stadt (eventuell Geschenk))",
  "Meteorfall (Höhle)",
  "Route 119 (Gras)",
  "Brutzelburg (Stadt (eventuell Geschenk))",
  "Route 120 (Gras)",
  "Route 121 (Gras)",
  "Seegrasulb City (Angeln)",
  "Route 122 (Angeln)",
  "Pyroberg (Höhle)",
  "Route 123 (Gras)",
  "Route 124 (Angeln)",
  "Route 125 (Angeln)",
  "Route 126 (Angeln)",
  "Xeneroville (Angeln)",
  "Route 127 (Angeln)",
  "Route 128 (Angeln)",
  "Route 129 (Angeln)",
  "Route 130 (Angeln)",
  "Route 131 (Angeln)",
  "Route 132 (Angeln)",
  "Route 133 (Angeln)",
  "Route 134 (Angeln)",
  "Seewoge Malvenfroh (Angeln)",
  "Siegesstraße (Höhle)",
  "Pokémon-Liga (Angel)"
];