export default [
    "Starter",
    "Route 19 (Gras)",
    "Floccesi-Ranch (Gras)",
    "Route 20 (Gras)",
    "Floccesi City (Geschenk)",
    "Avenitia (Geschenk)",
    "Gavina City (Geschenk)",
    "Genesungshöhle (Höhle)",
    "Virbank City (Angeln)",
    "Virbank-Komplex (Gras)",
    "Route 4 (Gras)",
    "Wüstenresort (Gras)",
    "Relikt-Schloss (Höhle)",
    "Route 16 (Gras)",
    "Marea City (Geschenk)",
    "Route 5 (Gras)",
    "Turnierhalle (Geschenk)",
    "Route 6 (Gras)",
    "Moor von Nevaio (Gras)",
    "Twist-Bergwerk (Höhle)",
    "Route 7 (Gras)",
    "Turm der Himmelsfeste (Turm)",
    "Route 13 (Gras)",
    "Lentimas-Tunnel (Höhle)",
    "Reverse Mountain (Höhle)",
    "Yamaji-Stadt (Geschenk)",
    "Route 12 (Gras)",
    "Stratos City (Geschenk)",
    "Route 9 (Gras)",
    "Route 11 (Gras)",
    "Route 23 (Gras)",
    "Siegesstraße (Höhle)",
    "Pokémon-Liga (Angeln)"
];